### ISSUE TITLE
Could not install simple storage

### ISSUE THREAD

**Issue by mariocalin** [perpetual-mobile/SimpleStorage#6]
Could not install package 'SimpleStorage 1.4.1'. You are trying to install this package into a project that targets 'portable-net45+win+wp80', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by markusressel** [comment]
I have the same issue. I'm trying to include SimpleStorage in a shared module via Nuget package manager.

`Could not install package 'SimpleStorage 1.4.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by Satindersatty** [comment]
Any update on this? I am also getting same error 

`Could not install package 'SimpleStorage 1.4.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

**Comment by emanon11** [comment]
I think you need to install the library twice.  Once in the Android section, once in the iOS section.  I had the same issue when I tried to install it in the Portable section (I'm using a PCL project).
