### ISSUE TITLE
How to store object?

### ISSUE THREAD

**Issue by Fate2018** [perpetual-mobile/SimpleStorage#8]
Is this possible to store object? if can, how to use put and get for Object value?

Thank

**Comment by rodja** [comment]
Have a look at the [Documentation](https://github.com/perpetual-mobile/SimpleStorage/blob/master/README.md):

    storage.Put<DateTime>("some timestamp", DateTime.Now);
    var value = storage.Get<DateTime>("some timestamp");

The class must have the `[Serializable]` attribute. For example: https://github.com/perpetual-mobile/SimpleStorage/blob/master/Tests/SerializationTests.cs#L24
